[package]
name = "orbtk_widgets"
version = "0.4.0-alpha.1"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Default widget library of OrbTk."
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
    "ecs"
]
edition = "2018"

[dependencies]
orbtk_core = { path = "../orbtk_core" }
