[package]
name = "orbtk_core"
version = "0.4.0-alpha.1"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Base components of OrbTk"
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
    "ecs"
]
edition = "2018"

[dependencies]
legion = "0.4.0"
