[package]
name = "orbtk"
version = "0.4.0-alpha.1"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
    "ecs"
]
edition = "2018"

[dependencies]
orbtk_core = { path = "../orbtk_core" }
orbtk_orbclient = { path = "../orbtk_orbclient" }
orbtk_tiny_skia = { path = "../orbtk_tiny_skia" }
orbtk_widgets = { path = "../orbtk_widgets" }